/* 2256x1504_70: Modeline 2256x1504_70 281.12 2256 2304 2336 2576 1504 1507 1517 1559 +hsync +vsync ratio=3:2 */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+10)
#define XPULSE 32
#define YPIX 1504
#define XPIX 2256
#define VFREQ 60
#define DPI 96
#define CLOCK 281120
#define VERSION 1
#define REVISION 3
#define XOFFSET 48
#define YOFFSET (63+3)
#define XY_RATIO XY_RATIO_3_2
#define YBLANK 55
#define XBLANK 320
#define TIMING_NAME "2256x1504_70"
#define XY_RATIO_3_2 4

#define XY_RATIO XY_RATIO_3_2
#include "edid.S"
